FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN apk add --no-cache tzdata curl && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
COPY target/snapcal-server.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-Xms200m", "-Xmx400m", "-Duser.timezone=Asia/Shanghai", "-jar", "app.jar"]
