USE snapcal; SET NAMES utf8mb4;
UPDATE sc_food SET emoji='🍚' WHERE name='米饭' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍚' WHERE name='糙米饭' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name='馒头' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍜' WHERE name='面条' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍜' WHERE name='米粉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍜' WHERE name='河粉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name='水饺' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name='包子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name='馄饨' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌽' WHERE name='玉米' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍠' WHERE name='红薯' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥔' WHERE name='土豆' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍠' WHERE name='芋头' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥖' WHERE name='油条' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍡' WHERE name='年糕' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍙' WHERE name='粽子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍜' WHERE name='凉皮' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍜' WHERE name='米线' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍝' WHERE name='意大利面' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍕' WHERE name='披萨' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍔' WHERE name='汉堡' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥪' WHERE name='三明治' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍣' WHERE name='寿司' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍙' WHERE name='饭团' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name='锅贴' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌯' WHERE name='春卷' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name='花卷' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name='豆包' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥚' WHERE name='鸡蛋' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥚' WHERE name='鸭蛋' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥚' WHERE name='鹌鹑蛋' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥚' WHERE name='皮蛋' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥚' WHERE name='咸鸭蛋' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥛' WHERE name='牛奶' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥛' WHERE name='酸奶' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧀' WHERE name='奶酪' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧀' WHERE name='芝士' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧈' WHERE name='黄油' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍦' WHERE name='冰淇淋' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥛' WHERE name='豆浆' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥛' WHERE name='豆奶' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥦' WHERE name='西兰花' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥦' WHERE name='菜花' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥕' WHERE name='胡萝卜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍅' WHERE name='番茄' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥒' WHERE name='黄瓜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍆' WHERE name='茄子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫑' WHERE name='青椒' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌶️' WHERE name='红椒' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧅' WHERE name='洋葱' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧄' WHERE name='大蒜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍄' WHERE name='蘑菇' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍄' WHERE name='香菇' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍄' WHERE name='金针菇' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍄' WHERE name='杏鲍菇' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍄' WHERE name='木耳' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍎' WHERE name='苹果' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍌' WHERE name='香蕉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍊' WHERE name='橙子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍊' WHERE name='橘子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍊' WHERE name='柚子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍇' WHERE name='葡萄' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍓' WHERE name='草莓' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫐' WHERE name='蓝莓' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍉' WHERE name='西瓜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍈' WHERE name='哈密瓜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥭' WHERE name='芒果' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍍' WHERE name='菠萝' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍑' WHERE name='桃子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍐' WHERE name='梨' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍒' WHERE name='樱桃' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥝' WHERE name='猕猴桃' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍋' WHERE name='柠檬' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥑' WHERE name='牛油果' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥥' WHERE name='椰子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍣' WHERE name='三文鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name='金枪鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name='鲈鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name='鳕鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name='带鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name='鲤鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name='鲫鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name='草鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦐' WHERE name='基围虾' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦞' WHERE name='小龙虾' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦀' WHERE name='螃蟹' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦪' WHERE name='扇贝' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦪' WHERE name='蛤蜊' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦪' WHERE name='生蚝' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦑' WHERE name='鱿鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐙' WHERE name='章鱼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦐' WHERE name='虾滑' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥜' WHERE name='花生' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name='核桃' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name='杏仁' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name='腰果' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name='开心果' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌻' WHERE name='瓜子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name='松子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name='板栗' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='莲子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍟' WHERE name='薯片' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍪' WHERE name='饼干' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍫' WHERE name='巧克力' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍬' WHERE name='奶糖' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🎂' WHERE name='蛋糕' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥧' WHERE name='蛋挞' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥮' WHERE name='月饼' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍿' WHERE name='爆米花' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍮' WHERE name='果冻' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥤' WHERE name='可乐' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥤' WHERE name='雪碧' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧃' WHERE name='橙汁' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧃' WHERE name='苹果汁' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='☕' WHERE name='咖啡' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧋' WHERE name='奶茶' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍵' WHERE name='绿茶' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍵' WHERE name='红茶' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍺' WHERE name='啤酒' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍷' WHERE name='红酒' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥃' WHERE name='白酒' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥥' WHERE name='椰汁' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍗' WHERE name='炸鸡' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍟' WHERE name='薯条' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍗' WHERE name='鸡块' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌭' WHERE name='热狗' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍚' WHERE name='蛋炒饭' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='豆腐' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='嫩豆腐' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='豆腐干' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='豆腐皮' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='腐竹' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥣' WHERE name='豆花' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='红豆' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='绿豆' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='黑豆' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍢' WHERE name='烧烤' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍢' WHERE name='烤串' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍲' WHERE name='火锅' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍲' WHERE name='麻辣烫' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍢' WHERE name='关东煮' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥗' WHERE name='沙拉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='菜心' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='生菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='白菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='菠菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='油菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='芹菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='韭菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌿' WHERE name='香菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='娃娃菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='油麦菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='空心菜' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name='芥蓝' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦆' WHERE name='烤鸭' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦆' WHERE name='鸭脖' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦆' WHERE name='鸭舌' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🕊️' WHERE name='鸽子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐴' WHERE name='驴肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐰' WHERE name='兔肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name='牛肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name='牛排' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥓' WHERE name='猪肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='排骨' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍗' WHERE name='鸡胸肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍗' WHERE name='鸡腿' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍗' WHERE name='鸡翅' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥓' WHERE name='培根' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='火腿' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌭' WHERE name='香肠' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌭' WHERE name='腊肠' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥫' WHERE name='午餐肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧆' WHERE name='肉丸' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='肉松' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍗' WHERE name='烤鸡' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦆' WHERE name='酱鸭' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥓' WHERE name='腊肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name='酱牛肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name='牛腩' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name='牛舌' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name='牛尾' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='肥肠' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='猪蹄' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='猪肝' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='猪血' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name='鸭血' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='羊排' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name='羊蝎子' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name='羊肉' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍎' WHERE name LIKE '%苹果%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍌' WHERE name LIKE '%香蕉%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍊' WHERE name LIKE '%橙%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍊' WHERE name LIKE '%橘%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍊' WHERE name LIKE '%柚%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍇' WHERE name LIKE '%葡萄%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫐' WHERE name LIKE '%莓%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍓' WHERE name LIKE '%草莓%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍉' WHERE name LIKE '%西瓜%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍈' WHERE name LIKE '%瓜%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥭' WHERE name LIKE '%芒果%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍍' WHERE name LIKE '%菠萝%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍑' WHERE name LIKE '%桃%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍐' WHERE name LIKE '%梨%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍒' WHERE name LIKE '%樱桃%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥝' WHERE name LIKE '%猕猴桃%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍋' WHERE name LIKE '%柠檬%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥥' WHERE name LIKE '%椰%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name LIKE '%荔枝%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name LIKE '%龙眼%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥚' WHERE name LIKE '%蛋%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥛' WHERE name LIKE '%奶%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧀' WHERE name LIKE '%酪%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧀' WHERE name LIKE '%芝士%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧈' WHERE name LIKE '%黄油%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍗' WHERE name LIKE '%鸡%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name LIKE '%牛%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥩' WHERE name LIKE '%羊%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥓' WHERE name LIKE '%猪%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦆' WHERE name LIKE '%鸭%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🐟' WHERE name LIKE '%鱼%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦐' WHERE name LIKE '%虾%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦀' WHERE name LIKE '%蟹%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦪' WHERE name LIKE '%贝%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🦑' WHERE name LIKE '%鱿%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍚' WHERE name LIKE '%米饭%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥣' WHERE name LIKE '%粥%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍜' WHERE name LIKE '%面%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍜' WHERE name LIKE '%粉%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name LIKE '%饺子%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥟' WHERE name LIKE '%包%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫓' WHERE name LIKE '%饼%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍚' WHERE name LIKE '%饭%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍞' WHERE name LIKE '%面包%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍔' WHERE name LIKE '%汉堡%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍠' WHERE name LIKE '%薯%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥔' WHERE name LIKE '%土豆%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌽' WHERE name LIKE '%玉米%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍆' WHERE name LIKE '%茄子%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍅' WHERE name LIKE '%番茄%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥒' WHERE name LIKE '%黄瓜%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌶️' WHERE name LIKE '%椒%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌶️' WHERE name LIKE '%辣%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧅' WHERE name LIKE '%葱%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧄' WHERE name LIKE '%蒜%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍄' WHERE name LIKE '%菇%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍄' WHERE name LIKE '%菌%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥬' WHERE name LIKE '%菜%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name LIKE '%豆%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫘' WHERE name LIKE '%豆腐%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍲' WHERE name LIKE '%汤%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍲' WHERE name LIKE '%火锅%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍲' WHERE name LIKE '%锅%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍢' WHERE name LIKE '%串%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍢' WHERE name LIKE '%烤%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🎂' WHERE name LIKE '%蛋糕%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍮' WHERE name LIKE '%甜%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍦' WHERE name LIKE '%冰淇淋%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍦' WHERE name LIKE '%雪糕%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍦' WHERE name LIKE '%冰%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍫' WHERE name LIKE '%巧克力%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍬' WHERE name LIKE '%糖%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍪' WHERE name LIKE '%饼干%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥮' WHERE name LIKE '%月饼%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥧' WHERE name LIKE '%蛋挞%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='☕' WHERE name LIKE '%咖啡%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍵' WHERE name LIKE '%茶%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧋' WHERE name LIKE '%奶茶%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍺' WHERE name LIKE '%酒%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍺' WHERE name LIKE '%啤%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥤' WHERE name LIKE '%可乐%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧃' WHERE name LIKE '%汁%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥤' WHERE name LIKE '%饮%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥜' WHERE name LIKE '%花%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name LIKE '%坚果%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name LIKE '%仁%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌻' WHERE name LIKE '%籽%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌰' WHERE name LIKE '%栗%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍮' WHERE name LIKE '%糕%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫙' WHERE name LIKE '%酱%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫗' WHERE name LIKE '%油%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🧂' WHERE name LIKE '%盐%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🫗' WHERE name LIKE '%醋%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥗' WHERE name LIKE '%沙拉%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍟' WHERE name LIKE '%炸%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍖' WHERE name LIKE '%排%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌭' WHERE name LIKE '%热狗%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍕' WHERE name LIKE '%披萨%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍣' WHERE name LIKE '%寿司%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍛' WHERE name LIKE '%咖喱%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🥪' WHERE name LIKE '%三明治%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🌯' WHERE name LIKE '%卷%' AND (emoji IS NULL OR emoji='🍽️');
UPDATE sc_food SET emoji='🍽️' WHERE emoji IS NULL;